server:
  port: 8083

# Configure Spring specific properties
spring:

  # Enable/Disable hot swapping
#  devtools:
#    restart:
#      enabled: true
#      log-condition-evaluation-delta: false

  # Datasource Configurations
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://127.0.0.1:27017/reactive
      database: reactive

  # Kafka Configuration
  cloud:
    function:
      definition: consumeTransaction
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          autoCreateTopics: false
      bindings:
        consumeTransaction-in-0:
          consumer:
            max-attempts: 3
            back-off-initial-interval: 100
          destination: transactions
          group: account
        transaction-out-0:
          destination: transactions