server:
  port: 8081

# Configure Spring specific properties
spring:
  # Datasource Configurations
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://mongodb:27017/reactive
      database: reactive

  # Kafka Configuration
  cloud:
    function:
      definition: consumeTransaction
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          autoCreateTopics: false
      bindings:
        consumeTransaction-in-0:
          consumer:
            max-attempts: 3
            back-off-initial-interval: 100
          destination: transactions
          group: notify
        transaction-out-0:
          destination: transactions